Repository AudiTranscribe/AudiTranscribe, pull requests merged in 2022-10, with the labels that each got.

#13 Version 0.8.1 Hotfix Staging Merge
  codecov.yml
  src/main/java/module-info.java
  src/main/java/site/overwrite/auditranscribe/io/data_files/DataFiles.java
  src/main/java/site/overwrite/auditranscribe/io/data_files/data_encapsulators/IconsData.java
  src/main/java/site/overwrite/auditranscribe/io/data_files/file_classes/IconsDataFile.java
  src/main/java/site/overwrite/auditranscribe/main_views/MainViewController.java
  src/main/java/site/overwrite/auditranscribe/main_views/TranscriptionViewController.java
  src/main/java/site/overwrite/auditranscribe/main_views/icon/IconHelpers.java
  src/main/java/site/overwrite/auditranscribe/main_views/icon/IconsData.java
Labels: release-merge

#14 Version 0.8.2 Staging Merge
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-and-upload-installers.yml
  .gitignore
  Other Files/Fix Note Delay View Files/Breakfast-Spectrogram-Compressed.jpg
  Other Files/Fix Note Delay View Files/Breakfast-Spectrogram-Original.png
  Other Files/Fix Note Delay View Files/Breakfast-Spectrogram-Resized.png
  Other Files/Fix Note Delay View Files/Breakfast.audt
  Other Files/Fix Note Delay View Files/Breakfast.mscz
  Other Files/Fix Note Delay View Files/Breakfast.wav
  codecov.yml
  pom.xml
  src/main/java/module-info.java
  src/main/java/site/overwrite/auditranscribe/audio/Audio.java
  src/main/java/site/overwrite/auditranscribe/audio/AudioProcessingMode.java
  src/main/java/site/overwrite/auditranscribe/io/ApplicationDirectory.java
  src/main/java/site/overwrite/auditranscribe/io/db/ProjectsDB.java
  src/main/java/site/overwrite/auditranscribe/main_views/TranscriptionViewController.java
  src/main/java/site/overwrite/auditranscribe/main_views/scene_switching/SceneSwitcher.java
  src/main/java/site/overwrite/auditranscribe/misc/CustomTask.java
  src/main/java/site/overwrite/auditranscribe/network/DownloadFileHandler.java
  src/main/java/site/overwrite/auditranscribe/network/DownloadTask.java
  src/main/java/site/overwrite/auditranscribe/plotting/PlottingStuffHandler.java
  src/main/java/site/overwrite/auditranscribe/setup_wizard/download_handlers/AbstractDownloadManager.java
  src/main/java/site/overwrite/auditranscribe/setup_wizard/download_handlers/AudioResourceDownloadManager.java
  src/main/java/site/overwrite/auditranscribe/setup_wizard/download_handlers/FFmpegDownloadManager.java
  src/main/java/site/overwrite/auditranscribe/setup_wizard/view_controllers/DownloadingAudioResourceViewController.java
  src/main/java/site/overwrite/auditranscribe/setup_wizard/view_controllers/DownloadingFFmpegViewController.java
  src/main/java/site/overwrite/auditranscribe/setup_wizard/view_controllers/FixNoteDelayViewController.java
  src/main/resources/site/overwrite/auditranscribe/setup-wizard-files/images/breakfast-spectrogram.jpg
  src/main/resources/site/overwrite/auditranscribe/views/fxml/setup-wizard/downloading-audio-resource-view.fxml
  src/main/resources/site/overwrite/auditranscribe/views/fxml/setup-wizard/downloading-ffmpeg-view.fxml
  src/main/resources/site/overwrite/auditranscribe/views/fxml/setup-wizard/fix-note-delay-view.fxml
  src/test/java/site/overwrite/auditranscribe/io/ApplicationDirectoryTest.java
  src/test/java/site/overwrite/auditranscribe/music/MusicKeyEstimatorTest.java
  src/test/java/site/overwrite/auditranscribe/music/bpm_estimation/BPMEstimatorTest.java
  src/test/java/site/overwrite/auditranscribe/music/bpm_estimation/OnsetTest.java
  src/test/java/site/overwrite/auditranscribe/network/DownloadFileHandlerTest.java
  src/test/java/site/overwrite/auditranscribe/spectrogram/SpectralHelpersTest.java
  src/test/java/site/overwrite/auditranscribe/spectrogram/spectral_representations/ChromaCQTTest.java
  src/test/java/site/overwrite/auditranscribe/spectrogram/spectral_representations/QTransformTests.java
Labels: release-merge

#19 Version 0.8.3 Staging Merge
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/workflows/build-and-upload-installers.yml
  .github/workflows/release.yml
  .github/workflows/run-tests-on-pull-to-staging.yml
  .github/workflows/run-tests-on-push-to-main.yml
  .github/workflows/run-tests.yml
  .releaserc
  Feature Plan.txt
  pom.xml
  src/main/resources/site/overwrite/auditranscribe/views/css/base.css
  src/main/resources/site/overwrite/auditranscribe/views/fonts/Roboto-Bold.ttf
  src/main/resources/site/overwrite/auditranscribe/views/fonts/Roboto-Italic.ttf
  src/main/resources/site/overwrite/auditranscribe/views/fonts/Roboto-Regular.ttf
  src/main/resources/site/overwrite/auditranscribe/views/fxml/main/project-setup-view.fxml
Labels: staging-merge

#21 Add Linux Support Progress To Main Repo
  README.md
  pom.xml
  src/main/java/site/overwrite/auditranscribe/audio/FFmpegHandler.java
  src/main/java/site/overwrite/auditranscribe/setup_wizard/SetupWizard.java
  src/main/java/site/overwrite/auditranscribe/setup_wizard/download_handlers/FFmpegDownloadManager.java
  src/main/java/site/overwrite/auditranscribe/system/OSMethods.java
  src/main/resources/site/overwrite/auditranscribe/views/fxml/setup-wizard/installing-ffmpeg-view.fxml
Labels: enhancement
